dist: xenial
language: python

python:
  - '3.7'
before_install:
  - sudo apt-get update -qq
install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.56.1/hugo_0.56.1_Linux-64bit.deb
  - sudo dpkg -i hugo_0.56.1_Linux-64bit.deb
  - sudo apt-get install -f
  - rm -f hugo_0.56.1_Linux-64bit.deb
script:
  - hugo
  - echo "$CNAME_URL" > public/CNAME
  - cd public
  - wget "https://github.com/BrennanMcDonald/BrennanMcDonaldIO/raw/master/Resume.pdf"

deploy:
  provider: s3
  access_key_id: AKIA4465SVUIEW7QISXE
  secret_access_key:
    secure: C/FxvqvR3dtlNoqlon44ajaPHA5UCIGXhY5wygFSBewxcCafZ4OdVakuV3oKghyCUa38RbhOUS+kvRDbkZtYMgXoJ5TBzYfzaKF8Z4LS+dIedDk2k44fM99dzcpSXWuN/ulTUnRAZ/J0GHFOcbHldL+uSxpY8FDTB2V9Jtal3gCNncUJFtUGhk5RTkHk37FXz7M0tUqhKBEXDQKvXZTTxNb88cA1JJMv9Bp6wN3C3Mlco5WwRwiVRGbjtsNEPu8rLd8grbF6UoelbpV7foOFJudL+WHC7496l7tYmECPk4LuGnjaHoXylaiWDaV+z8D59tiHstF5tYiJ/jPRdCDtruov0So+B9U0KylupQu1yE/XNCbwwVlO6+VNV9BQovpmVmW/7AA1BHmgA5FhRwQnwmMEp7jVHt9z+15DxWPEMv3M6HSb9BcYbOYC4ym0M6n98FoApBaNBXdbhnAJ72LsTNazCey6raLjNT0lsnr2ArQs77qUzytkT4hhjjq/x4p17XzM3SQ5CCxz+wSk9twesBPTxCkhbzGkjckAbDllbhvvllVMYPXTW5PTPwf4KKuMmhhElnOP75nUyVwiluA37l2vPrXHhop/SmECpp/c68xZ8aEnB68Psf+EEWjdj//SNhrm+zWewoTVuY67BppUYEPjzIeYWrNa/tJq9yQTpmE=
  bucket: brmc-static-website
  skip_cleanup: true
  local-dir: public
  on:
    repo: BrennanMcDonald/BrennanMcDonaldIO
