dist: xenial
language: python

python:
  - '3.7'
before_install:
  - sudo apt-get update -qq
install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.56.1/hugo_0.56.1_Linux-64bit.deb
  - sudo dpkg -i hugo_0.56.1_Linux-64bit.deb
  - sudo apt-get install -f
  - rm -f hugo_0.56.1_Linux-64bit.deb
script:
  - hugo
  - echo "$CNAME_URL" > public/CNAME
  - wget "https://github.com/BrennanMcDonald/BrennanMcDonaldIO/raw/master/Resume.pdf" -O public/Resume.pdf
  - cp keybase.txt public/keybase.txt

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS
  secret_access_key: $AWS_SECRET
  bucket: brmc-static-website
  skip_cleanup: true
  local-dir: public
  on:
    repo: BrennanMcDonald/BrennanMcDonaldIO
